### ISSUE TITLE
Issue: Flame-Out Detection does not detect if the grill actually ignites.

### ISSUE THREAD

**Issue by kennethLeeHarris** [muxall/RPTCQ-LCD#73]
Detection Enable Flame-Out : If the chamber temp is same as outside temp and doesn't drop, flame-out detection will not pause the cook.

**Comment by muxall** [comment]
Fixed in 0.504 and enhanced.
Flame-Out detection tests for three things:
1. Is Ignite Fire successful?  This is determined by a 25F rise in temp above the Outside Temperature.  Note – If your grill is in direct sunlight or has been previously used and is still hot, these may give a give a false positive to this test.  
2. Is the grill deliberately dropping temp?  Example: Going from 300F in Profile 1 to 180F in Profile 2 is a deliberate drop in temp.
3.  How long the auger has been running with the chamber temp lower than or equal to the target temp?  And, is the chamber temp climbing, dropping or  staying steady?  The Flame-Out Detect Time(m) is a timer that sets how long the grill is allowed to drop temperature (with the auger running) before it shuts the grill off.

**Comment by kennethLeeHarris** [comment]
I think I might need the real grill. I look at new manual and I put profile 1 at 300 for 10 minutes and then made profile 2 180 and put it on hold but the chamber temp just caught up with it 28 minutes later. I'm going to need to talk to you to see if I did this right.

**Comment by muxall** [comment]
You were the one that found this bug. Replace the simulator load with the real 0.506 load and then hit start. Since the simulator won't be running, it will never get above 80F and will fail Flame-On detection.

**Comment by kennethLeeHarris** [comment]
Tested it on 0.506 work great. It pause right after Igniter Fire mode.
